import exxon from '../images/exxon.jpg';
import mrs from '../images/mrs.jpg';
import rainOil from '../images/rain_oil.jpg';
import mobil from '../images/mobil.jpg';
import oilField1 from '../images/oil_field_1.jpg';
import oilField2 from '../images/oil_field_2.jpg';
import oilFieldSea from '../images/oil_field_sea.jpg';
import well1 from '../images/well_1.jpg';
import well2 from '../images/well_2.jpg';
import well3 from '../images/well_3.jpg';
import projectImg from '../images/projectImg.png';

export const reportData = [
  {
    id: '0',
    name: 'Gyan Report',
    author: 'Segun Oni',
    createdDate: '23 May, 2023',
    pdf: 'pdf',
  },
  {
    id: '1',
    name: 'Marwa Report',
    author: 'Adefaraja Sunny',
    createdDate: '23 May, 2023',
    pdf: 'pdf',
  },
  {
    id: '2',
    name: 'Mac Heirs Report',
    author: 'Benjamin Ogbeche',
    createdDate: '23 May, 2023',
    pdf: 'pdf',
  },
  {
    id: '3',
    name: 'Nvidia Report',
    author: 'Chukwu Okoro',
    createdDate: '23 May, 2023',
    pdf: 'pdf',
  },
];
export const projectData = [
  {
    id: '0',
    name: 'Ogara Project',
    status: 'In Progress',
    rig: 'MLS2',
    image: projectImg,
    startDate: '13 May, 2023',
    endDate: '13 May, 2023',
    createdDate: '23 May, 2023',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  },
  {
    id: '1',
    name: 'Japa Project',
    status: 'Paused',
    rig: 'QJP6',
    image: projectImg,
    startDate: '13 April, 2023',
    endDate: '25 August, 2023',
    createdDate: '23 May, 2023',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  },
  {
    id: '2',
    name: 'Imagba Project',
    status: 'Completed',
    rig: 'KPY8',
    image: projectImg,
    startDate: '13 April, 2023',
    endDate: '25 August, 2023',
    createdDate: '23 May, 2023',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  },
  {
    id: '3',
    name: 'Rosto Project',
    status: 'Completed',
    rig: 'RRTU',
    image: projectImg,
    startDate: '13 April, 2023',
    endDate: '25 August, 2023',
    createdDate: '23 May, 2023',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
  },
];

export const wellData = [
  {
    id: '0',
    name: 'Max Xen',
    wellType: 'Shoro',
    image: well1,
    longitude: 67.42,
    latitude: 13.76,
    createdDate: '13 May, 2023',
    treeSpecs: 'Blue Shell',
    bitSize: 34.56,
    currentStatus: 'Active',
    totalDepth: '345km',
    turbingSize: 23.56,
    flowStation: 'Zen lee',
    spudDate: '12 May, 2023',
    initialCompletionDate: '13 June, 2023',
    firstProductionDate: '24 march, 2023',
    casing: 34.56,
  },
  {
    id: '1',
    name: 'Xoxo RXC',
    wellType: 'Imela',
    image: well2,
    longitude: 83.31,
    latitude: 45.25,
    createdDate: '13 May, 2023',
    treeSpecs: 'Skey Save',
    bitSize: 78.46,
    currentStatus: 'Dull',
    totalDepth: '345km',
    turbingSize: 23.56,
    flowStation: 'Zen lee',
    spudDate: '12 May, 2023',
    initialCompletionDate: '13 June, 2023',
    firstProductionDate: '24 march, 2023',
    casing: 34.56,
  },
  {
    id: '2',
    name: 'Maple MLG',
    wellType: 'Segwest',
    image: well3,
    longitude: 96.82,
    latitude: 26.53,
    createdDate: '13 May, 2023',
    treeSpecs: 'Sig Mech',
    bitSize: 78.46,
    currentStatus: 'Dull',
    totalDepth: '345km',
    turbingSize: 23.56,
    flowStation: 'Zen lee',
    spudDate: '12 May, 2023',
    initialCompletionDate: '13 June, 2023',
    firstProductionDate: '24 march, 2023',
    casing: 34.56,
  },
  {
    id: '3',
    name: 'Pork GLk',
    wellType: 'MakaY',
    image: well1,
    longitude: 10.14,
    latitude: 60.12,
    createdDate: '13 May, 2023',
    treeSpecs: 'Mech ENG',
    bitSize: 78.46,
    currentStatus: 'Active',
    totalDepth: '345km',
    turbingSize: 23.56,
    flowStation: 'Zen lee',
    spudDate: '12 May, 2023',
    initialCompletionDate: '13 June, 2023',
    firstProductionDate: '24 march, 2023',
    casing: 34.56,
  },
];

export const fieldData = [
  {
    id: '0',
    name: 'Atoi',
    wells: 20,
    image: oilField1,
    longitude: 67.42,
    latitude: 13.76,
    createdDate: '13 May, 2023',
    superintendent: {
      name: 'Segun Oyebanji',
      email: 'segunoye@exxon.com',
      mobile: '+234 903 950 3369',
    },
    fieldWellData: [],
  },
  {
    id: '1',
    name: 'Lagbaja',
    wells: 10,
    image: oilField2,
    longitude: 33.33,
    latitude: 43.23,
    createdDate: '1 April, 2023',
    superintendent: {
      name: 'Samuel Okoro',
      email: 'samokoro@exxon.com',
      mobile: '+234 903 950 3369',
    },
    fieldWellData: [
      {
        id: '3',
        name: 'Pork GLk',
        wellType: 'MakaY',
        image: well1,
        longitude: 10.14,
        latitude: 60.12,
        createdDate: '13 May, 2023',
        treeSpecs: 'Mech ENG',
        bitSize: 78.46,
        currentStatus: 'Active',
        totalDepth: '345km',
        turbingSize: 23.56,
        flowStation: 'Zen lee',
        spudDate: '12 May, 2023',
        initialCompletionDate: '13 June, 2023',
        firstProductionDate: '24 march, 2023',
        casing: 34.56,
      },
    ],
  },
  {
    id: '2',
    name: 'Kimpasa',
    wells: 20,
    image: oilFieldSea,
    longitude: 87.54,
    latitude: 34.83,
    createdDate: '28 March, 2023',
    superintendent: {
      name: 'Muhammed Sanni',
      email: 'muhammedsan@exxon.com',
      mobile: '+234 903 950 3369',
    },
    fieldWellData: [
      {
        id: '1',
        name: 'Xoxo RXC',
        wellType: 'Imela',
        image: well2,
        longitude: 83.31,
        latitude: 45.25,
        createdDate: '13 May, 2023',
        treeSpecs: 'Skey Save',
        bitSize: 78.46,
        currentStatus: 'Dull',
        totalDepth: '345km',
        turbingSize: 23.56,
        flowStation: 'Zen lee',
        spudDate: '12 May, 2023',
        initialCompletionDate: '13 June, 2023',
        firstProductionDate: '24 march, 2023',
        casing: 34.56,
      },
      {
        id: '2',
        name: 'Maple MLG',
        wellType: 'Segwest',
        image: well3,
        longitude: 96.82,
        latitude: 26.53,
        createdDate: '13 May, 2023',
        treeSpecs: 'Sig Mech',
        bitSize: 78.46,
        currentStatus: 'Dull',
        totalDepth: '345km',
        turbingSize: 23.56,
        flowStation: 'Zen lee',
        spudDate: '12 May, 2023',
        initialCompletionDate: '13 June, 2023',
        firstProductionDate: '24 march, 2023',
        casing: 34.56,
      },
    ],
  },
  {
    id: '3',
    name: 'MLSQ',
    wells: 20,
    image: oilField1,
    longitude: 51.63,
    latitude: 38.23,
    createdDate: '11 January, 2023',
    superintendent: {
      name: 'Osasoyen Osaro',
      email: 'segunoye@exxon.com',
      mobile: '+234 903 950 3369',
    },
    fieldWellData: [...wellData],
  },
];

export const clientData = [
  {
    id: '0',
    name: 'Exxon Oil',
    contactperson: 'Segun Oni',
    website: 'https://exxon.com',
    image: exxon,
    mobile: '+234 903 950 3369',
    address: '23, ile-samaja close, off konibaje, street Ikeja, Lagos, Nigeria',
    createdDate: '23 May, 2023',
    clientFieldData: [...fieldData],
  },
  {
    id: '1',
    name: 'Mobil Oil',
    contactperson: 'Adefaraja Sunny',
    website: 'https://mobil.com',
    image: mobil,
    mobile: '+234 903 950 3369',
    address: '23, ile-samaja close, off konibaje, street Ikeja, Lagos, Nigeria',
    createdDate: '23 May, 2023',
    clientFieldData: [...fieldData],
  },
  {
    id: '2',
    name: 'Rain Oil',
    contactperson: 'Benjamin Ogbeche',
    website: 'https://rainoil.com',
    image: rainOil,
    mobile: '+234 903 950 3369',
    address: '23, ile-samaja close, off konibaje, street Ikeja, Lagos, Nigeria',
    createdDate: '23 May, 2023',
    clientFieldData: [],
  },
  {
    id: '3',
    name: 'MRS Oil',
    contactperson: 'Chukwu Okoro',
    website: 'https://mrs.com',
    image: mrs,
    mobile: '+234 903 950 3369',
    address: '23, ile-samaja close, off konibaje, street Ikeja, Lagos, Nigeria',
    createdDate: '23 May, 2023',
    clientFieldData: [
      {
        id: '2',
        name: 'Kimpasa',
        wells: 20,
        image: oilFieldSea,
        longitude: 87.54,
        latitude: 34.83,
        createdDate: '28 March, 2023',
        superintendent: {
          name: 'Muhammed Sanni',
          email: 'muhammedsan@exxon.com',
          mobile: '+234 903 950 3369',
        },
      },
      {
        id: '3',
        name: 'MLSQ',
        wells: 20,
        image: oilField1,
        longitude: 51.63,
        latitude: 38.23,
        createdDate: '11 January, 2023',
        superintendent: {
          name: 'Osasoyen Osaro',
          email: 'segunoye@exxon.com',
          mobile: '+234 903 950 3369',
        },
      },
    ],
  },
];
